//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Concept1.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Concept1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   New に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string _new {
            get {
                return ResourceManager.GetString("new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Back に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string action_back {
            get {
                return ResourceManager.GetString("action_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close Browser に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string action_close_browser {
            get {
                return ResourceManager.GetString("action_close_browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data Extraction に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string action_data_extraction {
            get {
                return ResourceManager.GetString("action_data_extraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter Data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string action_enter_data {
            get {
                return ResourceManager.GetString("action_enter_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search on Google に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string action_google_search {
            get {
                return ResourceManager.GetString("action_google_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Go to URL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string action_goto_url {
            get {
                return ResourceManager.GetString("action_goto_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Maximize Browser に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string action_maximize_browser {
            get {
                return ResourceManager.GetString("action_maximize_browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minimize Browser に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string action_minimize_browser {
            get {
                return ResourceManager.GetString("action_minimize_browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string action_next {
            get {
                return ResourceManager.GetString("action_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Browser に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string action_open_browser {
            get {
                return ResourceManager.GetString("action_open_browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Switch Browser に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string action_switch_browser {
            get {
                return ResourceManager.GetString("action_switch_browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search on Wikipedia に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string action_wikipedia_search {
            get {
                return ResourceManager.GetString("action_wikipedia_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yahoo! Japan Finance に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string action_yahoo_japan_finance {
            get {
                return ResourceManager.GetString("action_yahoo_japan_finance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search on Yahoo! Japan に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string action_yahoo_japan_search {
            get {
                return ResourceManager.GetString("action_yahoo_japan_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yahoo! Japan Transit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string action_yahoo_japan_transit {
            get {
                return ResourceManager.GetString("action_yahoo_japan_transit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Actions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string actions {
            get {
                return ResourceManager.GetString("actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Application に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string application_action {
            get {
                return ResourceManager.GetString("application_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Attachment に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string attachment {
            get {
                return ResourceManager.GetString("attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BCC に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string bcc {
            get {
                return ResourceManager.GetString("bcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Breakpoint に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string breakpoint {
            get {
                return ResourceManager.GetString("breakpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CC に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string cc {
            get {
                return ResourceManager.GetString("cc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Content に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string content {
            get {
                return ResourceManager.GetString("content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string data {
            get {
                return ResourceManager.GetString("data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lucida Sans に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DEFALT_FONT {
            get {
                return ResourceManager.GetString("DEFALT_FONT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Execute に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string execute {
            get {
                return ResourceManager.GetString("execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Favorite Actions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string favorite {
            get {
                return ResourceManager.GetString("favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   From に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string from {
            get {
                return ResourceManager.GetString("from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading Main Window.... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string loading_mainwindow {
            get {
                return ResourceManager.GetString("loading_mainwindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading UIA Instance.... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string loading_uia_instance {
            get {
                return ResourceManager.GetString("loading_uia_instance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading Web Automation Instance.... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string loading_web_automatinon_instance {
            get {
                return ResourceManager.GetString("loading_web_automatinon_instance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mail Actions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string mail_action {
            get {
                return ResourceManager.GetString("mail_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Address Email に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string mail_address {
            get {
                return ResourceManager.GetString("mail_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Email Property に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string mail_property {
            get {
                return ResourceManager.GetString("mail_property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Verifying Expense Claims に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string main_window_title {
            get {
                return ResourceManager.GetString("main_window_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Project に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string new_project {
            get {
                return ResourceManager.GetString("new_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Project に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string open_project {
            get {
                return ResourceManager.GetString("open_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Operation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string operation_action {
            get {
                return ResourceManager.GetString("operation_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Option に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string option {
            get {
                return ResourceManager.GetString("option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pause に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string pause {
            get {
                return ResourceManager.GetString("pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string play {
            get {
                return ResourceManager.GetString("play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Property に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string property {
            get {
                return ResourceManager.GetString("property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recent Actions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string recent_actions {
            get {
                return ResourceManager.GetString("recent_actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Redo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scenario に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string scenario {
            get {
                return ResourceManager.GetString("scenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select All に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string select_all {
            get {
                return ResourceManager.GetString("select_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string setting {
            get {
                return ResourceManager.GetString("setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SNS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string sns_action {
            get {
                return ResourceManager.GetString("sns_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string stop {
            get {
                return ResourceManager.GetString("stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Subject に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string subject {
            get {
                return ResourceManager.GetString("subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Template に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string template {
            get {
                return ResourceManager.GetString("template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Web Browser に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string web_browser_action {
            get {
                return ResourceManager.GetString("web_browser_action", resourceCulture);
            }
        }
    }
}
